Handlebars.registerHelper("key_value", function(obj, fn) {
    var buffer = "",
        key;

    for (key in obj) {
        if (obj.hasOwnProperty(key)) {
            buffer += fn({key: key, value: obj[key]});
        }
    }

    return buffer;
});

Template.item_select.items = function() {
	return {
		// Legendary Items
		"ageless-might": "Ageless Might",
		"ambos-pride": "Ambo's Pride",
		"andariels-visage": "Andariel's Visage",
		"anessazi-edge": "Anessazi Edge",
		"angel-hair-braid": "Angel Hair Braid",
		"aquila-cuirass": "Aquila Cuirass",
		"arreats-law": "Arreat's Law",
		"autumns-call": "Autumn's Call",
		"azurewrath": "Azurewrath",
		"bakkan-caster": "Bakkan Caster",
		"balance": "Balance",
		"balefire-caster": "Balefire Caster",
		"band-of-hollow-whispers": "Band of Hollow Whispers",
		"band-of-untold-secrets": "Band of Untold Secrets",
		"barter-town-pads": "Barter Town Pads",
		"bastions-revered": "Bastion's Revered",
		"beckon-sail": "Beckon Sail",
		"bezoar-stone": "Bezoar Stone",
		"bitterness": "Bitterness",
		"black-bone-arrows": "Black Bone Arrows",
		"blackguard": "Blackguard",
		"blackhand-key": "Blackhand Key",
		"blade-of-prophecy": "Blade of Prophecy",
		"blade-of-the-warlord": "Blade of the Warlord",
		"blind-faith": "Blind Faith",
		"blood-magic-blade": "Blood-Magic Blade",
		"boj-anglers": "Boj Anglers",
		"boneshatter": "Boneshatter",
		"broken-crown": "Broken Crown",
		"broken-promises": "Broken Promises",
		"bul-kathoss-wedding-band": "Bul-Kathos's Wedding Band",
		"buriza-do-kyanon": "Buriza-Do Kyanon",
		"butchers-carver": "Butcher's Carver",
		"calamity": "Calamity",
		"cape-of-the-dark-night": "Cape of the Dark Night",
		"cataclysm": "Cataclysm",
		"centurion": "Centurion",
		"chaingmail": "Chaingmail",
		"cindercoat": "Cindercoat",
		"cluckeye": "Cluckeye",
		"crushbane": "Crushbane",
		"crystal-fist": "Crystal Fist",
		"dark-mages-shade": "Dark Mage's Shade",
		"dawn": "Dawn",
		"dead-mans-legacy": "Dead Man's Legacy",
		"deadeye": "Deadeye",
		"death-watch-mantle": "Death Watch Mantle",
		"demon-hand": "Demon Hand",
		"demon-machine": "Demon Machine",
		"denial": "Denial",
		"depth-diggers": "Depth Diggers",
		"devil-tongue": "Devil Tongue",
		"doombringer": "Doombringer",
		"dread-iron": "Dread Iron",
		"earthshatter": "Earthshatter",
		"echoing-fury": "Echoing Fury",
		"empyrean-messenger": "Empyrean Messenger",
		"erlang-shen": "Erlang Shen",
		"eternal-union": "Eternal Union",
		"etrayu": "Etrayu",
		"eye-of-etlich": "Eye of Etlich",
		"faithful-memory": "Faithful Memory",
		"fire-brand": "Fire Brand",
		"fire-walkers": "Fire Walkers",
		"fjord-cutter": "Fjord Cutter",
		"flesh-tearer": "Flesh Tearer",
		"fleshrake": "Fleshrake",
		"fletchers-pride": "Fletcher's Pride",
		"flint-ripper-arrowheads": "Flint Ripper Arrowheads",
		"flying-dragon": "Flying Dragon",
		"fragment-of-destiny": "Fragment of Destiny",
		"frostburn-gauntlets": "Frostburn Gauntlets",
		"fury-of-the-vanished-peak": "Fury of the Vanished Peak",
		"gazing-demise": "Gazing Demise",
		"gehennas": "Gehennas",
		"genzaniku": "Genzaniku",
		"gesture-of-orpheus": "Gesture of Orpheus",
		"giant-skull": "Giant Skull",
		"girdle-of-giants": "Girdle of Giants",
		"gladiator-gauntlets": "Gladiator Gauntlets",
		"goldskin": "Goldskin",
		"goldwrap": "Goldwrap",
		"griswolds-masterpiece": "Griswold's Masterpiece",
		"gungdo-gear": "Gungdo Gear",
		"gyana-na-kashu": "Gyana Na Kashu",
		"hammer-jammers": "Hammer Jammers",
		"harvest-moon": "Harvest Moon",
		"heart-of-iron": "Heart of Iron",
		"heart-slaughter": "Heart Slaughter",
		"hellcat-waistguard": "Hellcat Waistguard",
		"hellfire-ring": "Hellfire Ring",
		"hellrack": "Hellrack",
		"hierophants-seal": "Hierophant's Seal",
		"holy-beacon": "Holy Beacon",
		"holy-point-shot": "Holy Point Shot",
		"homunculus": "Homunculus",
		"ice-climbers": "Ice Climbers",
		"incense-torch-of-the-grand-temple": "Incense Torch of the Grand Temple",
		"ivory-tower": "Ivory Tower",
		"izzuccob": "Izzuccob",
		"justice-lantern": "Justice Lantern",
		"kill": "Kill",
		"kotuurs-brace": "Kotuur's Brace",
		"kymbos-gold": "Kymbo's Gold",
		"lacuni-prowlers": "Lacuni Prowlers",
		"lai-yuis-taiji": "Lai Yui's Taiji",
		"lamentation": "Lamentation",
		"last-breath": "Last Breath",
		"leorics-crown": "Leoric's Crown",
		"leorics-signet": "Leoric's Signet",
		"lidless-wall": "Lidless Wall",
		"logans-claw": "Logan's Claw",
		"longshot": "Longshot",
		"lost-boys": "Lost Boys",
		"lut-socks": "Lut Socks",
		"madstone": "Madstone",
		"magefist": "Magefist",
		"maloths-focus": "Maloth's Focus",
		"manald-heal": "Manald Heal",
		"manticore": "Manticore",
		"maras-kaleidoscope": "Mara's Kaleidoscope",
		"maximus": "Maximus",
		"mempo-of-twilight": "Mempo of Twilight",
		"messerschmidts-reaver": "Messerschmidt's Reaver",
		"monster-hunter": "Monster Hunter",
		"moon-slayer": "Moon Slayer",
		"moonlight-ward": "Moonlight Ward",
		"nagelring": "Nagelring",
		"nailbiter": "Nailbiter",
		"neanderthal": "Neanderthal",
		"nutcracker": "Nutcracker",
		"obsidian-ring-of-the-zodiac": "Obsidian Ring of the Zodiac",
		"oculus-ring": "Oculus Ring",
		"odyn-son": "Odyn Son",
		"ouroboros": "Ouroboros",
		"pendergrasps": "Pendergrasps",
		"pig-sticker": "Pig Sticker",
		"pledge-of-caldeum": "Pledge of Caldeum",
		"pox-faulds": "Pox Faulds",
		"pride-of-cassius": "Pride of Cassius",
		"promise-of-glory": "Promise of Glory",
		"pus-spitter": "Pus Spitter",
		"puzzle-ring": "Puzzle Ring",
		"quetzalcoatl": "Quetzalcoatl",
		"quick-draw-belt": "Quick Draw Belt",
		"rabid-strike": "Rabid Strike",
		"robes-of-the-rydraelm": "Robes of the Rydraelm",
		"rondals-locket": "Rondal's Locket",
		"rozpedins-staff": "Rozpedin's Staff",
		"ruinstoke": "Ruinstoke",
		"saffron-wrap": "Saffron Wrap",
		"scarbringer": "Scarbringer",
		"schaeferss-hammer": "Schaefers's Hammer",
		"scourge": "Scourge",
		"scrimshaw": "Scrimshaw",
		"see-no-evil": "See No Evil",
		"seven-sins": "Seven Sins",
		"sever": "Sever",
		"silver-star-piercers": "Silver Star Piercers",
		"sin-seekers": "Sin Seekers",
		"singularity": "Singularity",
		"skorn": "Skorn",
		"skull-grasp": "Skull Grasp",
		"sky-splitter": "Sky Splitter",
		"skycutter": "Skycutter",
		"skywarden": "Skywarden",
		"slave-bonds": "Slave Bonds",
		"sledge-fist": "Sledge fist",
		"sledge-of-athskeleng": "Sledge of Athskeleng",
		"sloraks-madness": "Slorak's Madness",
		"spectrum": "Spectrum",
		"split-tusk": "Split Tusk",
		"squirts-necklace": "Squirt's Necklace",
		"standoff": "Standoff",
		"starfire": "Starfire",
		"starspine": "Starspine",
		"steady-strikers": "Steady Strikers",
		"stolen-ring": "Stolen Ring",
		"stone-gauntlets": "Stone Gauntlets",
		"stone-of-jordan": "Stone of Jordan",
		"storm-crow": "Storm Crow",
		"stormshield": "Stormshield",
		"string-of-ears": "String of Ears",
		"strongarm-bracers": "Strongarm Bracers",
		"sun-keeper": "Sun Keeper",
		"swamp-land-waders": "Swamp Land Waders",
		"talisman-of-aranoch": "Talisman of Aranoch",
		"tasker-and-theo-": "Tasker and Theo ",
		"telrandens-hand": "Telranden's Hand",
		"the-ancient-bonesaber-of-zumakalis": "The Ancient Bonesaber of Zumakalis",
		"the-barber": "The Barber",
		"the-broken-staff": "The Broken Staff",
		"the-burning-axe-of-sankis": "The Burning Axe of Sankis",
		"the-butchers-sickle": "The Butcher's Sickle",
		"the-clouds-and-the-moon": "The Clouds and the Moon",
		"the-crudest-boots": "The Crudest Boots",
		"the-executioner": "The Executioner",
		"the-eye-of-the-storm": "The Eye of the Storm",
		"the-fist-of-azturrasq": "The Fist of Az'Turrasq",
		"the-flavor-of-time": "The Flavor of Time",
		"the-gavel-of-judgment": "The Gavel of Judgment",
		"the-gidbinn": "The Gidbinn",
		"the-grand-vizier": "The Grand Vizier",
		"the-grandfather": "The Grandfather",
		"the-grin-reaper": "The Grin Reaper",
		"the-helm-of-command": "The Helm of Command",
		"the-horadric-hamburger": "The Horadric Hamburger",
		"the-inquisitor": "The Inquisitor",
		"the-magi": "The Magi",
		"the-minds-eye": "The Mind's Eye",
		"the-oculus": "The Oculus",
		"the-paddle": "The Paddle",
		"the-ravens-wing": "The Raven's Wing",
		"the-star-of-azkaranth": "The Star of Azkaranth",
		"the-sultan-of-blinding-sand": "The Sultan of Blinding Sand",
		"the-swami-": "The Swami ",
		"the-three-hundredth-spear": "The Three Hundredth Spear",
		"the-tormentor": "The Tormentor",
		"the-undisputed-champion": "The Undisputed Champion",
		"the-wedge": "The Wedge",
		"the-witching-hour": "The Witching Hour",
		"the-zweihander": "The Zweihander",
		"thing-of-the-deep": "Thing of the Deep",
		"thunder-gods-vigor": "Thunder God's Vigor",
		"tiklandian-visage": "Tiklandian Visage",
		"triumvirate": "Triumvirate",
		"tyraels-might": "Tyrael's Might",
		"tzo-krins-gaze": "Tzo Krin's Gaze",
		"uhkapian-serpent": "Uhkapian Serpent",
		"umbral-oath": "Umbral Oath",
		"unending-war": "Unending War",
		"unity": "Unity",
		"uskang": "Uskang",
		"venomhusk": "Venomhusk",
		"vigilance": "Vigilance",
		"vigilante-belt": "Vigilante Belt",
		"vile-ward": "Vile Ward",
		"visage-of-giyua": "Visage of Giyua",
		"wall-of-bone": "Wall of Bone",
		"warmonger": "Warmonger",
		"wildwood": "Wildwood",
		"windforce": "Windforce",
		"winter-flurry": "Winter Flurry",
		"wizardspike": "Wizardspike",
		"won-khim-lau": "Won Khim Lau",
		"wondrous-deflectors": "Wondrous Deflectors",
		"wormwood": "Wormwood",
		"wrath-of-the-bone-king": "Wrath of the Bone King",
		"xephirian-amulet": "Xephirian Amulet",
		"ziggurat-tooth": "Ziggurat Tooth",
		// Set Items
		"ashearas-gait": "Asheara's Gait",
		"ashearas-guard": "Asheara's Guard",
		"ashearas-iron-fist": "Asheara's Iron Fist",
		"ashearas-tracks": "Asheara's Tracks",
		"aughilds-dominion": "Aughild's Dominion",
		"aughilds-peak": "Aughild's Peak",
		"aughilds-reign": "Aughild's Reign",
		"aughilds-ultimatum": "Aughild's Ultimatum",
		"blackthornes-duncraig-cross": "Blackthorne's Duncraig Cross",
		"blackthornes-jousting-mail": "Blackthorne's Jousting Mail",
		"blackthornes-notched-belt": "Blackthorne's Notched Belt",
		"blackthornes-spurs": "Blackthorne's Spurs",
		"blackthornes-surcoat": "Blackthorne's Surcoat",
		"borns-heart-of-steel": "Born's Heart of Steel",
		"borns-impunity": "Born's Impunity",
		"borns-searing-spite": "Born's Searing Spite",
		"bul-kathoss-solemn-vow": "Bul-Kathos's Solemn Vow",
		"bul-kathoss-warrior-blood": "Bul-Kathos's Warrior Blood",
		"cains-memory": "Cain's Memory",
		"cains-robes": "Cain's Robes",
		"cains-sandals": "Cain's Sandals",
		"cains-scribe": "Cain's Scribe",
		"captain-crimsons-bowsprit": "Captain Crimson's Bowsprit",
		"captain-crimsons-satin-sash": "Captain Crimson's Satin Sash",
		"captain-crimsons-whalers": "Captain Crimson's Whalers",
		"chantodos-force": "Chantodo's Force",
		"chantodos-will": "Chantodo's Will",
		"danettas-revenge": "Danetta's Revenge",
		"danettas-spite": "Danetta's Spite",
		"demons-flight": "Demon's Flight",
		"demons-heart": "Demon's Heart",
		"demons-lock": "Demon's Lock",
		"demons-revenge": "Demon's Revenge",
		"demons-scale": "Demon's Scale",
		"guardians-deflector": "Guardian's Deflector",
		"guardians-foresight": "Guardian's Foresight",
		"guardians-sheath": "Guardian's Sheath",
		"hallowed-defender": "Hallowed Defender",
		"hallowed-hand": "Hallowed Hand",
		"hallowed-judgment": "Hallowed Judgment",
		"hallowed-reckoning": "Hallowed Reckoning",
		"hallowed-salvation": "Hallowed Salvation",
		"hallowed-scepter": "Hallowed Scepter",
		"hallowed-storm": "Hallowed Storm",
		"immortal-kings-boulder-breaker": "Immortal King's Boulder Breaker",
		"immortal-kings-eternal-reign": "Immortal King's Eternal Reign",
		"immortal-kings-irons": "Immortal King's Irons",
		"immortal-kings-stride": "Immortal King's Stride",
		"immortal-kings-tribal-binding": "Immortal King's Tribal Binding",
		"immortal-kings-triumph": "Immortal King's Triumph",
		"innas-favor": "Inna's Favor",
		"innas-radiance": "Inna's Radiance",
		"innas-reach": "Inna's Reach",
		"innas-temperance": "Inna's Temperance",
		"innas-vast-expanse": "Inna's Vast Expanse",
		"litany-of-the-undaunted": "Litany of the Undaunted",
		"manajumas-carving-knife": "Manajuma's Carving Knife",
		"manajumas-gory-fetch": "Manajuma's Gory Fetch",
		"natalyas-bloody-footprints": "Natalya's Bloody Footprints",
		"natalyas-embrace": "Natalya's Embrace",
		"natalyas-reflection": "Natalya's Reflection",
		"natalyas-sight": "Natalya's Sight",
		"natalyas-slayer": "Natalya's Slayer",
		"sages-gesture": "Sage's Gesture",
		"sages-journey": "Sage's Journey",
		"sages-orbit": "Sage's Orbit",
		"shenlongs-fist-of-legend": "Shenlong's Fist of Legend",
		"shenlongs-relentless-assault": "Shenlong's Relentless Assault",
		"tal-rashas-allegiance": "Tal Rasha's Allegiance",
		"tal-rashas-brace": "Tal Rasha's Brace",
		"tal-rashas-guise-of-wisdom": "Tal Rasha's Guise of Wisdom",
		"tal-rashas-relentless-pursuit": "Tal Rasha's Relentless Pursuit",
		"tal-rashas-unwavering-glare": "Tal Rasha's Unwavering Glare",
		"the-compass-rose": "The Compass Rose",
		"the-travelers-pledge": "The Traveler's Pledge",
		"the-wailing-host": "The Wailing Host",
		"zunimassas-marrow": "Zunimassa's Marrow",
		"zunimassas-pox": "Zunimassa's Pox",
		"zunimassas-string-of-skulls": "Zunimassa's String of Skulls",
		"zunimassas-trail": "Zunimassa's Trail",
		"zunimassas-vision": "Zunimassa's Vision",
		// Normal Items
		"2h-axe": "2h axe",
		"2h-mace": "2h mace",
		"2h-mighty": "2h mighty",
		"2h-sword": "2h sword",
		"amulet": "amulet",
		"axe": "axe",
		"belt": "belt",
		"boots": "boots",
		"bow": "bow",
		"bracers": "bracers",
		"ceremonial-knife": "ceremonial knife",
		"chest": "chest",
		"cloak": "cloak",
		"crossbow": "crossbow",
		"dagger": "dagger",
		"daibo": "daibo",
		"fist-weapon": "fist weapon",
		"gloves": "gloves",
		"hand-crossbow": "hand crossbow",
		"helm": "helm",
		"mace": "mace",
		"mighty-belt": "mighty belt",
		"mighty-weapon": "mighty weapon",
		"mojo": "mojo",
		"pants": "pants",
		"polearm": "polearm",
		"quiver": "quiver",
		"ring": "ring",
		"shield": "shield",
		"shoulders": "shoulders",
		"source": "source",
		"spear": "spear",
		"spirit-stone": "spirit stone",
		"staff": "staff",
		"sword": "sword",
		"voodoo-mask": "voodoo mask",
		"wand": "wand",
		"wizard-hat": "wizard hat"
	};
};
